name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: configure SSH Deamon
      run: |
        echo "CASignatureAlgorithms +ssh-rsa" | sudo tee -a /etc/ssh/sshd_config
        sudo systemctl restart sshd
    - name: SSH into server Pull Git
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_PRODUCTION }}
        username: ${{ secrets.USER_PRODUCTION_PULL }}
        passphrase: ${{ secrets.PSS_PRODUCTION_PULL }}
        key: ${{ secrets.SSH_PRODUCTION_PULL }}
        port: 538
        script: |
          cd ${{ secrets.PATH_PRODUCTION }}
          git pull origin master
